### ISSUE TITLE
Calcolare quante e quali fontane sono raggiungibili da un punto

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/FontanellePalermo#14]
Mi spiego con un esempio.

Abbiamo due fontane, una è il pallino arancione e una è quella verde.

Le aree da cui sono raggiungibile rispettivamente in 5 minuti sono delimitate con gli stessi colori.

L'area indicata dalla freccia, non è toccata da alcun pallino, "deve contare" 2, perché è l'area da cui 2 fontane (la verde e l'arancione) sono raggiungibili in 5 minuti.

Al click sul punto in rosso l'ideale sarebbe: sapere quante fontane sono raggiungibili in X minuti e sapere che sono la fontana verde e quella arancione.

![image](https://user-images.githubusercontent.com/30607/64074814-c0a72280-ccb0-11e9-993e-decfb67567b8.png)

**Comment by pigreco** [comment]
Soluzione usando **QGIS**:
1. importo il file **tp_300.geojson** presente nella cartella `./analisi/isolinee/output`;
2. da strumenti di processing avvio geo-Algoritmo `Unione`*, inserisco il _layer di ingresso_  (**tp_300.geojson**), come layer di sovrapposizione lascio vuoto, infine inserisco percorso per output file, `eseguo`;
3. ottengo un nuovo livello che ho chiamato nome **unione** con tutte le info che ci servono, occorre però tirarle fuori;

![image](https://user-images.githubusercontent.com/7631137/64078516-ebf33700-ccdb-11e9-9dc4-58ebf21d7ea6.png)

4. aggiungo tre nuovi campi (**nro**: numero aree sovrapposte clippate; **ids**: ids isoArea; **indirizzo_i**: indirizzi fontane);
5. popolo, usando il field calc, il campo **nro** con la seguente espressione:

```
-- conteggio aree uguali sovrapposte
count(  
expression:="ID" ,  -- ID della isolinea
group_by:= $area  -- superficie area isolinea clippate
)
```
6. popolo, usando il filed calc, il campo **ids** con la seguente espressione:

```
-- calcolo gli ids per ogni isoarea clippata
replace(                              -- elimino la prima parte degli ID tp_
concatenate(                      -- concateno il risultato
expression:="ID",               -- ID isolinee
group_by:=$area,               -- raggruppo per superficie
concatenator:=','), 'tp_',''
)
```
7. faccio pulizia: ricerco le aree con valore più piccolo di 0.01 con la seguente espressione `$area < 0.01` e poi cancello gli elementi risultanti dalla selezione (221 elementi, nel nostro caso);
8. creo un campo virtuale **cv** e lo popolo con l'espressione `replace( "n" ,'tp_','')` che mi servirà successivamente per fare un `join` con il layer **fontanelle** (campi per join: `cv` e `n`);
9. faccio la `join`;
10. popolo, usando il filed calc, il campo **indzzo_i** del layer `unione` con la seguente espressione:

```
 replace(
 concatenate( 
 expression:= "fontanelle_Indirizzo" , 
 group_by:= "ids" ,
 concatenator:=' | '), ' | ', '\n' ) 
```
11. tolgo la `join` e cancello il campo virtuale `cv` precedentemente creato;
12. da strumenti di processing, cerco **dissolvi** utilizzando il layer **unione** e come campo **ids** ottenendo un nuovo livello che chiamo `computo`;
---
Ho creato una [sottocartella ](https://github.com/opendatasicilia/FontanellePalermo/tree/master/analisi/computi)`computi` nella cartella `analisi`: dentro i file e un progetto qgs



---

```
*This algorithm checks overlaps between features within the Input layer and creates separate features for overlapping and non-overlapping parts. The area of overlap will create as many identical overlapping features as there are features that participate in that overlap.
An Overlay layer can also be used, in which case features from each layer are split at their overlap with features from the other one, creating a layer containing all the portions from both Input and Overlay layers. The attribute table of the Union layer is filled with attribute values from the respective original layer for non-overlapping features, and attribute values from both layers for overlapping features.
```
link: http://changelog.qgis.org/en/qgis/version/3.2.0/#union-algorithm-with-single-layer

**Comment by pigreco** [comment]
Modello grafico con QGIS:
![image](https://user-images.githubusercontent.com/7631137/64120274-10164d00-cd9c-11e9-8037-7a9b65d417b2.png)

[script.py](https://github.com/opendatasicilia/FontanellePalermo/files/3566324/computo_nro_iso_sovrapposte.zip)
