### ISSUE TITLE
Controllare interdistanza tra le fontanelle

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/FontanellePalermo#15]
Ho trovato casualmente due fontanelle a meno di un metro:

![image](https://user-images.githubusercontent.com/7631137/64075290-a8d29d00-ccb6-11e9-8e09-61f3dd6c0efb.png)

occorre una verifica delle interdistanze tra le fontanelle, una distanza inferiore (come in questo caso) al metro crea dei dubbi.

**Comment by gbvitrano** [comment]
I civici sono sbagliati. a poca distanza ci sono o meglio dovrebbero esserci due fontanelle.
una esistente e la seconda in corso restauro (secondo amap) la localizzazione di amap è un file di progetto e non di rilievo
![2019-09-01_12h46_01](https://user-images.githubusercontent.com/20488693/64075384-d704ac80-ccb7-11e9-877e-37aad78aa818.jpg)

**Comment by pigreco** [comment]
Con [QGIS ](https://qgis.org/it/site/)ho calcolato la Matrice delle distanze:

![image](https://user-images.githubusercontent.com/7631137/64075395-fb608900-ccb7-11e9-850a-79a75abc043c.png)

quelle selezionate (in blu) sono le due fontanelle (n 31 e 127)

**EDIT**: calcolo matrice delle distanze in SQL

```sql
SELECT
 a.n as id1,  b.n as id2,
 st_distance(a.geometry, b.geometry, 1) AS dist
FROM
 fontanelle as a,  fontanelle as b
WHERE a.n <> b.n
```

**Comment by pigreco** [comment]
Grazie alla matrice delle distanze siamo certi che in un solo caso ( n 31 e 127 -  [fontanelle.csv](https://github.com/opendatasicilia/FontanellePalermo/blob/master/analisi/isolinee/risorse/fontanelle.csv)) l'interdistanza è sotto il metro.
