### ISSUE TITLE
Nome fontanelle nel popup isocrone

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/FontanellePalermo#17]
Nel popup che si apre nelle isocrone, al posto dell'id della fontanella non si potrebbe mettere il nome della via?
Un utente o turista non capirebbe l'id o il numero della fontanlla :-) e magari con un elenco verticale 

![2019-09-01_14h17_57](https://user-images.githubusercontent.com/20488693/64076336-d96d0380-ccc3-11e9-967c-55d7ad9f2f4f.png)

**Comment by pigreco** [comment]
@gbvitrano 
allego primo test `muto` se va bene descrivo meglio il processo
![image](https://user-images.githubusercontent.com/7631137/64076761-1e476900-ccc9-11e9-81b3-d31dab4ef456.png)

[come_piace_andy_elenco_aCapo.zip](https://github.com/opendatasicilia/FontanellePalermo/files/3563490/come_piace_andy_elenco_aCapo.zip)

**Comment by gbvitrano** [comment]
Non funziona, probabilmente quando umap importa il file mette tutto su un rigo
![2019-09-01_15h03_25](https://user-images.githubusercontent.com/20488693/64076809-d5dc7b00-ccc9-11e9-809b-f6dd7ec2d02b.png)

![2019-09-01_15h06_21](https://user-images.githubusercontent.com/20488693/64076827-14723580-ccca-11e9-9093-560fb280feb4.png)

**Comment by gbvitrano** [comment]
**Funziona!!**
![2019-09-01_15h21_18](https://user-images.githubusercontent.com/20488693/64077042-4be1e180-cccc-11e9-9eeb-a87d1579d79f.png)

sbagliavo io a fare leggere ad umap la colonna sbagliata :-)

**Comment by gbvitrano** [comment]
**Idea per inserire un link alle fontanelle**
al file originale ho aggiunto 4 colonne **id** **id1** **map** ed **osm**
![2019-09-01_17h23_19](https://user-images.githubusercontent.com/20488693/64078624-345f2480-ccdd-11e9-8a10-c10e3a80723e.png)
[Fontanelle_link.zip](https://github.com/opendatasicilia/FontanellePalermo/files/3563638/Fontanelle_link.zip)
usando questo file per le fontanelle e il file tp_300.shp

possiamo aggiungere due nuove colonne con i link nello stesso ordine della collonna **capo**?
![2019-09-01_17h26_54](https://user-images.githubusercontent.com/20488693/64078660-b4858a00-ccdd-11e9-8909-29676f007666.png)

**Comment by pigreco** [comment]
Caro @gbvitrano 
ho aggiunto anche le colonne per i link
trovi un file geojson pronto all'uso [qui](https://github.com/opendatasicilia/FontanellePalermo/blob/master/analisi/computi/computo_con_link.geojson)
