### ISSUE TITLE
Mappa di progetto: crearne una da zero

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/FontanellePalermo#19]
Caro @gpirrotta ,
le API di here impongono il riuso basato su loro prodotti.

Non puoi mettere l'URL XYZ su uMAP perché metteresti in chiaro le chiavi delle API dell'utente here.

Allora dovresti riprodurre le poche feature che servono in Leaflet (con qgis2web ad esempio), con una mappa di sfondo a tuo piacere. Per l'accesso ai dati delle fontanelle, fatti un file statico, senza pensare a come accedere a un CSV su gdrive.

Una volta che per te è ok, fai un fischio e io la modificherò per la parte di "protezione" delle API.

Qui c'è un esempio di codice funzionante, per accedere alle basi here via proxy https://github.com/opendatasicilia/FontanellePalermo/tree/master/web/esempioCiaoMondoProxy

**Comment by gbvitrano** [comment]
ok domani ci lavoro :-)

**Comment by aborruso** [comment]
@gbvitrano ho creato il branch gh-pages, dove se vuoi puoi mettere tutto

L'indirizzo di test sarà https://opendatasicilia.github.io/FontanellePalermo/

**Comment by aborruso** [comment]
La chiudo, perché la base c'è
