### ISSUE TITLE
problema durante geo-algoritmo Unione di QGIS

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/FontanellePalermo#20]
Durante la fase di calcolo del geo-algoritmo Unione, QGIS segnala un problema su una feature del file `tp_300` e di conseguenza non lo processa:

![image](https://user-images.githubusercontent.com/7631137/64080369-a6426880-ccf3-11e9-9d0f-d5a0b2a98d20.png)

ecco la feature

![image](https://user-images.githubusercontent.com/7631137/64080418-3bddf800-ccf4-11e9-81d1-adba46ca5b68.png)

sembra mancare solo la parte visibile!!!

Occorre capire il perché!

**Comment by aborruso** [comment]
Il layer di base non sembra avere errori. @pigreco potresti estrarre dallo shapefile soltanto questo gruppetto e rifare il test.

Se non va a buon fine (che è quello che avverrà) potresti aprire una issue su QGIS.

**Comment by pigreco** [comment]
Ho estratto solo il gruppetto di isocrone (e salvate come geojson), sono 8:
![image](https://user-images.githubusercontent.com/7631137/64094676-c0fcf780-cd5c-11e9-9d5a-8067b956ed3a.png)

il risultato del geo-algoritmo Unione restituisce 65 elementi (sembrano tutti):
![image](https://user-images.githubusercontent.com/7631137/64094900-85166200-cd5d-11e9-9073-7513a64eeba5.png)

il risultato del geo-algoritmo Unione nel caso generale restituisce (dopo pulitura), per quel gruppetto, 62 elementi; effettuando la pulitura anche nel gruppetto isolato ottengo 63 elementi 
e quello in più è quello che manca nel caso generale

![image](https://user-images.githubusercontent.com/7631137/64095252-9744d000-cd5e-11e9-9d01-fc6757182aa6.png)

quindi sembra funzionare tutto bene isolando il gruppetto.

**Comment by aborruso** [comment]
Caro totò per me invece c'è lo stesso problema e manca la solita porzione.

Lo vedi in questo video http://youtu.be/Qzo0gR0-yNk?hd=1

L'ho fatto su [questo file](https://github.com/opendatasicilia/FontanellePalermo/files/3564826/tmp_dbg.zip)

**Comment by pigreco** [comment]
La cosa diventa sempre più strana,
con il tuo file (come lo estrapoli? da dove lo estrapoli??) ottengo nuovamente errore;

seleziono gruppetto e poi esporto in shp solo la selezione (parto dal file presente nel repo github)
avviando Unione NON ottengo nessun errore (Test fatti in QGIS 3.14.11 ltr Madeira e 3.8.2 Zanzibar)

qui mio file:
[aaaa.zip](https://github.com/opendatasicilia/FontanellePalermo/files/3564894/aaaa.zip)

**Comment by aborruso** [comment]
Caro @pigreco ,
parto dal file sorgente `FontanellePalermo/analisi/isolinee/output/tp_300.shp`, seleziono e salvo con nome la selezione in formato shp.

Tutto qui

![image](https://user-images.githubusercontent.com/30607/64097598-fc032900-cd64-11e9-9f92-d8abdac99279.png)

**Comment by pigreco** [comment]
io uso `FontanellePalermo/analisi/isolinee/output/tp_300.shp`

**Comment by pigreco** [comment]
Ho approfondito un po': ho tolto il gruppetto incriminato dall'intero file e avviato Unione, ottengo altri errori.
Generano errori questi due gruppetti di isocrone

![image](https://user-images.githubusercontent.com/7631137/64098748-f4914f00-cd67-11e9-966f-765ee2718c40.png)

infatti eliminandoli non si verifica nessun errore,
ecco il file
[aaaa.zip](https://github.com/opendatasicilia/FontanellePalermo/files/3564999/aaaa.zip)

**Comment by aborruso** [comment]
> Ho approfondito un po': ho tolto il gruppetto incriminato dall'intero file e avviato Unione, ottengo altri errori.

Io, come ti dicevo, invierei la nota su QGIS. Perché non danno errori ai controlli.

**Comment by aborruso** [comment]
> io uso `FontanellePalermo/analisi/isolinee/output/tp_300.shp`

Anche io, scusami, ho scritto male

**Comment by pigreco** [comment]
Ho aperto [issue ](https://github.com/qgis/QGIS/issues/31528)nel repo di QGIS, nel frattempo ho trovato questa soluzione:

utilizzando gli strumenti di processing:
1. `Da poligono a linee`

![image](https://user-images.githubusercontent.com/7631137/64114607-b7d84e80-cd8d-11e9-9e94-b814c4d71bb8.png)

2. `Poligonizza`, usando il layer del punto 1:

![image](https://user-images.githubusercontent.com/7631137/64115684-8dd45b80-cd90-11e9-9f59-b62b84bfdb66.png)

3. `Unione` usando come layer di sovrapposizione quello del punto 2:

![image](https://user-images.githubusercontent.com/7631137/64115834-eefc2f00-cd90-11e9-8d0b-2073ca7155d7.png)

Modellatore grafico di QGIS:

![image](https://user-images.githubusercontent.com/7631137/64116107-aabd5e80-cd91-11e9-9490-8bad60a16dc9.png)

[script.py](https://github.com/opendatasicilia/FontanellePalermo/files/3566123/alternativa_unione_un_solo_layer.zip)

**Comment by pigreco** [comment]
issue correlata [#31552](https://github.com/qgis/QGIS/issues/31552)

**Comment by pigreco** [comment]
![image](https://user-images.githubusercontent.com/7631137/64323687-3e2aa580-cfc5-11e9-9603-f8cd9695b1e7.png)

**Comment by pigreco** [comment]
Non credo ci siano altre novità nella issue correlata nel repo QGIS.
Chiudo
