### ISSUE TITLE
SpatiaLite e campo multilinea

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/FontanellePalermo#21]
Ho un campo TEXT popolato da

```
FONTANELLA | FONTANA
```
esiste un modo per ottenere un campo multilinea come sotto??

```
FONTANELLA
FONTANA
```

- dataset esempio

```
rowid,pk,nro,nome
41,45,1,120,FONTANELLA
42,46,2,121,145,FONTANELLA | FONTANELLA
43,47,1,121,FONTANELLA
44,48,1,145,FONTANELLA
45,50,1,121,FONTANELLA
46,51,3,121,145,146,FONTANELLA | FONTANELLA | FONTANELLA
47,52,2,121,146,FONTANELLA | FONTANELLA
48,53,2,112,120,FONTANELLA | FONTANELLA
49,54,1,112,FONTANELLA
```
cosa cerco di ottenere:
![image](https://user-images.githubusercontent.com/7631137/64181416-b595f300-ce66-11e9-8c18-6a691367f6af.png)

qui database per testing
https://github.com/opendatasicilia/FontanellePalermo/blob/master/risorse/appuntiSQL/db_fontanelle_link.sqlite

qui scriptSQL che genera la tabella:
https://github.com/opendatasicilia/FontanellePalermo/blob/master/risorse/appuntiSQL/scriptSQL_link.sql

**Comment by pigreco** [comment]
da una rapida prova questo non funziona:
https://stackoverflow.com/questions/47227684/how-to-insert-a-new-line-n-character-in-sqlite

**Comment by aborruso** [comment]
@pigreco quando dici non funzionante, cosa intendi??

Cosa ti aspetti di ottenere? Se descrivi tutto il flusso, è meglio

**Comment by pigreco** [comment]
Il mio punto di partenza è

```sql
SELECT c.pk_elem AS pk_elem, 
			group_concat(p."Nome", " | ") AS "Nome_i",
			group_concat(p."Indirizzo", " | ") AS "Indirizzo_i",
			group_concat(p."Coordinate", " | ") AS "Coordinate_s",
			group_concat(p."maps", " | ") AS "maps_s",
			group_concat(p."osm", " | ") AS "osm_s", 
			count(*) AS nro, 
			group_concat(REPLACE(id,'tp_','')) AS ids 
    FROM centroid_inner c, tp_300_link p
    WHERE st_contains (p.geom,c.geom)
    GROUP BY 1
    ORDER BY 3 desc;
```

pensavo che bastasse sostituire a `" | "` questo `"|| char(10) ||"` ma ottengo `FONTANELLA||char(10)||FONTANELLA`

in realtà nel post di SE suggeriscono di fare un `INSERT INTO` e quindi devo capire come farlo in questo contesto.

Scusa la issue confusionaria.

EDIT: aggiungo anche che non so bene se nella GUI di spatialite è visibile la multilinea. :-(

**Comment by pigreco** [comment]
Chiudo issue perché non sono sicuro si possa fare in spatialite_gui.

**Comment by aborruso** [comment]
La riapro. Se ho compreso quello che vuoi fare, si può fare

**Comment by aborruso** [comment]
Ciao Totò,
la cosa è fattibile, l'importante è che ci sia il ritorno a capo tra doppi apici.

[Questo](https://github.com/opendatasicilia/FontanellePalermo/files/3579449/esempio.zip) un file di esempio di output, che puoi usare in input.

![image](https://user-images.githubusercontent.com/30607/64345144-13097b80-cff0-11e9-9327-e900b6ef5a08.png)


![image](https://user-images.githubusercontent.com/30607/64345081-f53c1680-cfef-11e9-8687-f6347d2061af.png)

**Comment by pigreco** [comment]
Caro @aborruso 

> la cosa è fattibile, l'importante è che ci sia il ritorno a capo tra doppi apici.

Funziona!!!

![image](https://user-images.githubusercontent.com/7631137/64528064-de573600-d307-11e9-8dce-5cd042424a0f.png)

lo script SQL va scritto cosi, come tu suggerisci:

```sql
    (SELECT c.pk_elem AS pk_elem, 
						group_concat(p."Tipologia","  
						") AS "Tipologia_s",
						group_concat(p."Indirizzo"," 
						") AS "Indirizzo_i",
						group_concat(p."Coordinate"," 
						") AS "Coordinate_s",
						group_concat(p."UPL"," 
						") AS "UPLs",
						group_concat(p."UPL_nome"," 
						") AS "UPL_nome_s",
						group_concat(p."Quartiere"," 
						") AS "Quartiere_i",
						group_concat(p."Circoscrizione"," 
						") AS "Circoscrizione_i",
						group_concat(p."id_Quartie"," 
						") AS "id_Quartie_s",
						group_concat(p."CAP"," 
						") AS "CAPs",
						group_concat(p."indizizzo_link"," 
						") AS "indirizzo_links",
						count(*) AS nro, 
						group_concat(REPLACE("tp_id",'tp_','')) AS ids 
    FROM centroid_inner c, tp_600_link_gmaps p
    WHERE st_contains (p.geom,c.geom)
    GROUP BY 1
    ORDER BY 3 desc) t1
```

grazie!
