### ISSUE TITLE
Poligoni Tp 600

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/FontanellePalermo#27]
Le isocrone tp 600 andrebbero trattate come le Tp 300 allego il file con i poligoni della differenza tra tp 600 e tp 300 [differenza.zip](https://github.com/opendatasicilia/FontanellePalermo/files/3580367/differenza.zip)
![photo6019275324384195293](https://user-images.githubusercontent.com/20488693/64362251-7a362880-d00e-11e9-88ea-f45d187b4894.jpg)
- 1 dividere il poligono in più poligoni
- 2 contare quante e quali fontane sono raggiungibili #14 
- 3 aggiungere i link dell'indirizzo, come fatto in tp 300

non è necessario unire il risultato di questo file con il file tp_300, in questo caso è meglio se i due file sono separati

**Comment by aborruso** [comment]
Se deve essere fatto per il 600 bisogna partire da questo shp https://github.com/opendatasicilia/FontanellePalermo/blob/master/analisi/isolinee/output/tp_600.shp

E poi si buca. Ma si può applicare la stessa procedura del 300.

@pigreco se è cosa lunga, io faccio in pochi minuti con mapshaper

**Comment by pigreco** [comment]
@aborruso 
ho fatto una rapida prova con QGIS ma ottengo errori, se puoi procedi tu, grazie

**Comment by aborruso** [comment]
@gbvitrano ecco lo shp https://github.com/opendatasicilia/FontanellePalermo/blob/master/analisi/isolinee/output/output_tp_600.shp

Non ho fatto molti test.

Notte

**Comment by gbvitrano** [comment]
> 
> 
> @gbvitrano ecco lo shp https://github.com/opendatasicilia/FontanellePalermo/blob/master/analisi/isolinee/output/output_tp_600.shp
> 
> Non ho fatto molti test.
> 
> Notte

Grazie :-) 
@pigreco adesso i pologoni del file di @aborruso andrebbero bucati con i tp_300 e aggiunte le vie con i link come hai fatto con i tp_300, quando un pò di tempo lo puoi fare?

**Comment by gbvitrano** [comment]
Ho fatto un test per bucare i poligoni Tp 600
Prima di procedere ho fatto correggere a QGIS alcune geometrie di **output_tp_600**

![2019-09-06_19h48_44](https://user-images.githubusercontent.com/20488693/64449288-d2892b00-d0df-11e9-983c-9ad4dd51e91a.png)
durante il processo mi ha dato qualche errore.
Esempio nel file ottenuto manca il poligono  indicato

![immagine](https://user-images.githubusercontent.com/20488693/64449395-11b77c00-d0e0-11e9-97f9-f3aa3cf34182.png)

per bucare i poligoni ho usato il geoprocessing **Differenza**

![2019-09-06_19h56_25](https://user-images.githubusercontent.com/20488693/64449597-9609ff00-d0e0-11e9-82f7-4db5d1bed94f.png)

e qui l'errore

![2019-09-06_19h57_10](https://user-images.githubusercontent.com/20488693/64449647-b639be00-d0e0-11e9-81d7-b0e27f82777e.png)

**File ottenuto**
[tp_600_bucati.zip](https://github.com/opendatasicilia/FontanellePalermo/files/3585069/tp_600_bucati.zip)

andrebbero solo aggiunte le vie con i link :-)

**Comment by pigreco** [comment]
@gbvitrano ecco lo shapefile
https://github.com/opendatasicilia/FontanellePalermo/blob/master/analisi/isolinee/output/tp_600_bucato.shp

non ho fatto molte verifiche.

**Comment by gbvitrano** [comment]
I poligoni Tp 600 sono stati caricati in mappa
Grazie :-)

![2019-09-08_08h16_02](https://user-images.githubusercontent.com/20488693/64484351-1a5b9f80-d211-11e9-91ea-5012b0c7980c.png)

chiudo issue
