### ISSUE TITLE
"progetto base": link errato in apertura

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/FontanellePalermo#3]
Ciao @pigreco al lancio ottengo il messaggio di sotto.

È corretto?

Grazie

![image](https://user-images.githubusercontent.com/30607/63747701-0c6c5d00-c8a8-11e9-9c14-458dba6f9dc3.png)

**Comment by pigreco** [comment]
Ciao @aborruso 
purtroppo è normale, i virtual layer lavorano SOLO con percorsi assoluti almeno per le versioni <=3.8

Appena posso aggirerò il problema.
Il virtual layer serviva solo per creare un poligono con il solo perimetro della città di Palermo.

**Comment by aborruso** [comment]
Prima di lanciare il processo, volevo capire se stavo "rompendo" cose.

Chiudo
