### ISSUE TITLE
[OSM] fontanelle mappate

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/FontanellePalermo#36]
Ciao,
sto usando questa **_query overpass_** per vedere le fontanelle mappate a Palermo città:

```
<osm-script output="xml" timeout="25">
    <union>
        <query type="node">
            <has-kv k="amenity" v="fountain"/>
            <bbox-query {{bbox}}/>
        </query>
    </union>
    <union>
        <item/>
        <recurse type="down"/>
    </union>
    <print mode="body"/>
</osm-script>
```

[output](https://overpass-turbo.eu/s/Rbm):

![image](https://user-images.githubusercontent.com/7631137/75614052-bd440500-5b34-11ea-9006-be109bdc182f.png)

la `key` e `value` sono corrette??

l'output che cerco è corretto??

**Comment by pigreco** [comment]
Caro @aborruso 
Unica fontanella (mappata in OSM) di acqua potabile entro un raggio di 30 m (rispetto alla fontanelle AMAP) è:

![image](https://user-images.githubusercontent.com/7631137/75622700-8ce77f80-5ba3-11ea-9392-a6baffcdda9a.png)

coord: `38.09751700, 13.41649242`
osm_id : `4654014892`

per tutte le altre non trovo nessun legame.

**Comment by aborruso** [comment]
Caro @pigreco la ricerca giusta è quella per `drinking_water`: http://overpass-turbo.eu/s/RbM

Mi sembra che qualcuna coincidente con la banca dati AMAP ci sia.

Grazie

**Comment by pigreco** [comment]
>ricerca giusta è quella per drinking_water: http://overpass-turbo.eu/s/RbM

grazie, ricontrollo tutto.

**Comment by pigreco** [comment]
query [overpass ](http://overpass-turbo.eu/s/RbM) usata:

```
/*
This has been generated by the overpass-turbo wizard.
The original search was:
“"drinking water"”
*/
[out:json][timeout:25];
// gather results
(
  // query part for: “"drinking water"”
  node["amenity"="drinking_water"]({{bbox}});
);
// print results
out body;
>;
out skel qt;
```

[AMAP_nonPresenti_in_OSM_entro_25m_4326.txt](https://github.com/opendatasicilia/FontanellePalermo/files/4271661/AMAP_nonPresenti_in_OSM_entro_25m_4326.txt)

Per determinare il file CSV:
1. buffer 25 m su punti OSM estratti con query overpass;
2. selezionato i punti AMAP `contenuti` nel buffer;
3. seleziona inversa per ottenere tutte le fontanelle oltre i 25 m;

**Comment by aborruso** [comment]
Grazie
