### ISSUE TITLE
Lancio del processo: è normale Fontanelle non sia valorizzato?

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/FontanellePalermo#4]
Ciao @pigreco al lancio è grigio. È normale?

![image](https://user-images.githubusercontent.com/30607/63749790-78e95b00-c8ac-11e9-8f66-4ff4275834f9.png)

**Comment by pigreco** [comment]
Sì, devi scegliere tu il layer.
È un geoprocessing e i layer vanno scelti da noi dalla comboBox.

**Comment by aborruso** [comment]
Che peccato, che non sia possibile anche fissarlo.

Grazie

**Comment by pigreco** [comment]
Sinceramente non lo so se è possibile fissarlo, devo approfondire.
Ha senso fissarlo se il layer di input fosse solo uno, in generale sono molti.

grazie per i test
