### ISSUE TITLE
Routing fontanelle e civici di Palermo 

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/FontanellePalermo#7]
Abbiamo a disposizione vari strati informativi:
1. fontanelle 
2. civici
3. stradario
questi strati potrebbero essere utilizzati per fare una analisi di **routing** per capire ogni fontanella quanti civici puo' servire entro una certa distanza fissata (es:400 m) e di conseguenza capire se la distribuzione attuale delle fontanelle è ottimale oppure occorre realizzarne altre.

**Comment by aborruso** [comment]
Quale stradario pensi di usare? Openstreetmap?

**Comment by pigreco** [comment]
> Quale stradario pensi di usare? Openstreetmap?

sì, perché è topologicamente corretto e ci fa risparmiare tempo.

**EDIT:**
http://download.geofabrik.de/

**Comment by aborruso** [comment]
**Aggiornamento**: ho aperto nuovo thread per esplodere quanto scritto sotto #8 

---

Aggiungo un altro spunto:

- a partire da un grafo stradale, per ogni fontana si calcolano le aree di isodistanza (l'area coperta in 2 km a piedi) e/o di isotempo (l'area coperta in 10 minuti a piedi). I 2 km e i 10 minuti sono soltanto un esempio;
- si fa l'unione delle aree calcolate, una per quelle a tempo e una per quella a distanza;
- si incrociano queste due con il limite comunale di Palermo e si estraggono le aree in cui non si arriva per distanza o per tempo

Sotto un esempio di isodistanza a Berlino

![image](https://user-images.githubusercontent.com/30607/63949679-0ed2e080-ca7b-11e9-9e1d-17cd60490732.png)

**Comment by pigreco** [comment]
**SpatiaLite** gestisce un modulo di “routing” denominato **VirtualNetwork** (rete virtuale). Lavorando su una rete arbitraria questo modulo consente di identificare le connessioni di percorso minimo (shortest path) con una semplice interrogazione SQL. Il modulo VirtualNetwork si appoggia su algoritmi sofisticati ed altamente ottimizzati, così è veramente veloce ed efficiente anche nel caso di reti di grande dimensione.

Ecco un primo risultato:
![image](https://user-images.githubusercontent.com/7631137/63970408-5457d380-caa4-11e9-95f8-48cf6ec996a0.png)
i pallini verdi sono i civici e in rosso le fontanelle.

```
SELECT *
FROM roads_network_net
WHERE NodeFrom = 2838 AND Cost <=400;
```

**NodeFrom = Fontanella**

Lo screenshot rappresenta tutti i civici che distano `<= 400 m` della fontanella.

Nel passo successivo occorre iterare la query per tutte le fontanelle.
Presto maggiori dettagli.

**Comment by aborruso** [comment]
Molto bello @pigreco

**Comment by pigreco** [comment]
Aggiorno un po' lo stato di avanzamento:
1. Alla rete stradale OSM ho aggiunto gli oltre 1.2 M numeri civici;
2. ho creato segmento che unisce il numero civico all'asse stradale (il criterio è quello di minima distanza tra civico e asse stradale);

![image](https://user-images.githubusercontent.com/7631137/64103114-b6992880-cd71-11e9-8858-21061b5a1d2c.png)

3. ho creato la roads_network e calcolato le isocrone 400 m e 800 m

![image](https://user-images.githubusercontent.com/7631137/64103487-a9306e00-cd72-11e9-8be2-ea42710db542.png)

**Comment by aborruso** [comment]
La chiuderei. Che dici @pigreco ?

**Comment by pigreco** [comment]
ok!
