### ISSUE TITLE
Calcolo delle aree servite "male"

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/FontanellePalermo#8]
Lo spunto mi viene dalla issue #7 di @pigreco 

Ecco l'idea di base:

- a partire da un grafo stradale, per ogni fontana si calcolano le aree di isodistanza (l'area coperta in 2 km a piedi) e/o di isotempo (l'area coperta in 10 minuti a piedi). I 2 km e i 10 minuti sono soltanto un esempio;
- si fa l'unione delle aree calcolate, una per quelle a tempo e una per quella a distanza;
- si incrociano queste due con il limite comunale di Palermo e si estraggono le aree in cui non si arriva per distanza o per tempo

Sotto un esempio di isodistanza a Berlino

![image](https://user-images.githubusercontent.com/30607/63949679-0ed2e080-ca7b-11e9-9e1d-17cd60490732.png)

Il calcolo è semplice, sfruttando uno dei servizi disponibili online.
Vorrei una mano a capire come impostare i parametri per una **prima elaborazione**. Ha più senso partire dalla isodistanza? Da calcolare sia a piedi che in auto? Quale distanza/tempo mettere come "sopportabile"?

**Comment by pigreco** [comment]
caro @aborruso 
> Ha più senso partire dalla isodistanza? Da calcolare sia a piedi che in auto? Quale distanza/tempo mettere come "sopportabile"?

Forse è meglio utilizzare il tempo e quindi fisserei 10 minuti come mia soglia personale.

**Comment by aborruso** [comment]
> Forse è meglio utilizzare il tempo e quindi fisserei 10 minuti come mia soglia personale.

In auto e a piedi? 10 minuti per arrivare o andata e ritorno (quindi usare 5 min nel calcolo)?

**Comment by pigreco** [comment]
> In auto e a piedi? 10 minuti per arrivare o andata e ritorno (quindi usare 5 min nel calcolo)?

a piedi 10 min andata e ritorno (5 min calcolo) 
in auto è molto diverso: auto è sottocasa?? occorre tenere presente i sensi di marcia, il parcheggio vicino alla fontanella ecc..

**Comment by michelangelopavia** [comment]
Ciao @aborruso 
> Vorrei una mano a capire come impostare i parametri per una **prima elaborazione**. Ha più senso partire dalla isodistanza? Da calcolare sia a piedi che in auto? Quale distanza/tempo mettere come "sopportabile"?

a mio avviso direi 400mt o 5 minuti a piedi , 10mt in auto nel senso che serve un parcheggio accanto alle fontanelle per accostare, riempire il bidone e andare. A parte la considerazione sull'essere a Palermo e le persone camminano poco c'è un problema in città di qualità dei percorsi pedonali che fanno sembrare tratti di 400mt percorsi infernali brutti e pericolosi, e con il carico di 5/10kg di bidone ancora peggio. 

Starei dunque basso, non più di 400mt.

**Comment by aborruso** [comment]
Ok, facciamo il calcolo di 5 minuti e 400 mt a piedi.
E per l'auto 10 minuti, in un mondo ideale, considerando i sensi di marcia. 

Vediamo che esce al primo giro e poi ci ragioniamo di nuovo insieme.

E benvenuto @michelangelopavia !

**Comment by aborruso** [comment]
Primo output: aree raggiungibili in 5 minuti a piedi dalle fontane.
A prima vista, non bello.

Servizio usato: [HERE](https://developer.here.com/documentation/routing/topics/example-isoline-simple-time.html)

![image](https://user-images.githubusercontent.com/30607/63979530-63954c00-cab9-11e9-89bb-c1440ac9f11e.png)

**Comment by michelangelopavia** [comment]
Non bello ma verosimile direi. Grazie del benvenuto!

**Comment by aborruso** [comment]
Ecco le aree da cui si raggiungono in 10 e 5 minuti a piedi. Maggiori dettagli [qui](https://github.com/opendatasicilia/FontanellePalermo/tree/master/analisi#calcolo-tramite-le-api-di-here) 

![image](https://user-images.githubusercontent.com/30607/64013611-7abb5480-cb20-11e9-8ac4-d9f6e38b6031.png)

**Comment by aborruso** [comment]
Sono stati eseguiti i seguenti calcoli:

- a piedi in 5 e 10 minuti
- in auto (senza tenere conto del traffico in 5 e 10 minuti)
- in auto, tenendo conto del traffico in 5 minuti

Con le API utilizzate non si possono calcolare isocrone in bici o tramite mezzi pubblici.

Quindi chiudo la issue e non appena possibile faccio l'indice descrittivo di quanto creato
